# Generated by Django 3.1.5 on 2021-02-03 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundChannel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[-a-z0-9_]+$', 'Please insert efficient id!')], verbose_name='Inbound Channel ID')),
                ('folder', models.CharField(blank=True, max_length=100, verbose_name='Folder')),
                ('filename_pattern', models.CharField(max_length=100, verbose_name='Filename Pattern')),
                ('remove_files', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Remove Files')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, verbose_name='Task ID')),
                ('inbound_channel_id', models.CharField(blank=True, max_length=50, verbose_name='Inbound Channel ID')),
                ('inbound_trading_partner_id', models.CharField(blank=True, max_length=50, verbose_name='Inbound Trading Partner ID')),
                ('outbound_channel_id', models.CharField(blank=True, max_length=50, verbose_name='Outbound Channel ID')),
                ('outbound_trading_partner_id', models.CharField(blank=True, max_length=50, verbose_name='Outbound Trading Partner ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('inbound_filename', models.CharField(blank=True, max_length=100, verbose_name='Inbound Filename')),
                ('inbound_folder', models.CharField(blank=True, max_length=100, verbose_name='Inbound Folder')),
                ('outbound_filename', models.CharField(blank=True, max_length=100, verbose_name='Outbound Filename')),
                ('outbound_folder', models.CharField(blank=True, max_length=100, verbose_name='Outbound Folder')),
                ('log_message', models.CharField(blank=True, max_length=100, verbose_name='Log Message')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundChannel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[-a-z0-9_]+$', 'Please insert efficient id!')], verbose_name='Outbound Channel ID')),
                ('folder', models.CharField(blank=True, max_length=100, verbose_name='Folder')),
                ('archive_folder', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[-a-z0-9_/]*$', 'Please insert efficient value!')], verbose_name='Archive Folder')),
                ('filename_pattern', models.CharField(max_length=100, verbose_name='Filename Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='TradingPartner',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[-a-z0-9_]+$', 'Please insert efficient id!')], verbose_name='Trading Partner ID')),
                ('sftp_hostname', models.CharField(blank=True, max_length=100, verbose_name='SFTP Hostname')),
                ('sftp_username', models.CharField(blank=True, max_length=50, verbose_name='SFTP Username')),
                ('sftp_password', models.CharField(blank=True, max_length=50, verbose_name='SFTP Password')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[-a-z0-9_]+$', 'Please insert efficient id!')], verbose_name='Task ID')),
                ('notification_script', models.CharField(blank=True, max_length=200, verbose_name='Notification Script')),
                ('inbound_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='science.inboundchannel', verbose_name='Inbound Channel ID')),
                ('outbound_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='science.outboundchannel', verbose_name='Outbound Channel ID')),
            ],
        ),
        migrations.AddField(
            model_name='outboundchannel',
            name='trading_partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='science.tradingpartner', verbose_name='Trading Partner ID'),
        ),
        migrations.AddField(
            model_name='inboundchannel',
            name='trading_partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='science.tradingpartner', verbose_name='Trading Partner ID'),
        ),
    ]
